version: 2.1
executors:
  build-chromium:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build-for-android:
    executor: build-chromium
    steps:
      - run: |
          sudo apt install -y git
          git clone https://github.com/termux-user-repository/tur.git --branch test-chromium-headless ~/tur
          cd ~/tur
          ./setup-environment.sh
          ./scripts/run-docker.sh ./build-package.sh -I -a aarch64 chromium && ls -l debs
      - store_artifacts:
          path: ~/tur/debs/chromium*
          destination: chromium.deb

workflows:
  build-chromium:
    jobs:
      - build-for-android
